### ISSUE TITLE
RecyclerView Animation

### ISSUE THREAD

**Issue by 16meyrat** [willowtreeapps/spruce-android#81]
When a RecyclerView is animated, it is first fully displayed, then disapears, and then the animation starts. Is their a way to launch the animation as soon as the Activity starts ?

**Comment by bret-fears** [comment]
The current example for recycler is calling the animation start in onLayoutChildren which, as you can see, is applying the animation to the children rather than when they are added. The proper path to take is to run the animation from a RecyclerView.ItemAnimator#animateAdd() call so the children are animated when they are added. 

The drawback to using animateAdd is it'd apply the animations one at a time rather than to the group. 

The path moving forward is to add native RecyclerView.ItemAnimator support which will hopefully be available in an upcoming release. 

Thank you for calling this out!

**Comment by filol** [comment]
+1
I look forward to this new version

**Comment by rf43** [comment]
@bret-fears We could probably label this as an `Enhancement`

**Comment by tfonfara** [comment]
+1 looking forward to that!

**Comment by tfonfara** [comment]
I think I found an easier solution for that problem than https://github.com/willowtreeapps/spruce-android/pull/79 is.

In `Spruce.java:71` the animation will be delayed using `setStartDelay()`. This also delays the "setup" of the items which means the initial hiding.

If I change now

`animatorCopy.setStartDelay(childView.getTimeOffset());`

to

`animatorCopy.start();`
`animatorCopy.cancel();`
`animatorCopy.setStartDelay(childView.getTimeOffset());`

the animation starts (items will be hidden) but the actual animation is cancelled immediately. After that I can add the start delay and the full animation will be played as expected.

What do you think about that?
CC: @bret-fears 

PS: Looks like this change only affects the initial recycler view animation, all other animations (recycler view onClick animation, all sort animations) still work fine and as previously in the sample app.

**Comment by bret-fears** [comment]
@tfonfara I like it! It's simple and solves the issue described by @lokither

**Comment by tfonfara** [comment]
@bret-fears I'm pleased to hear that :) I saw that you declined your pr, will you integrate my approach into the main code?

**Comment by bret-fears** [comment]
@tfonfara you're welcome to submit a pull request. Otherwise, I'll gladly add that suggested change when I have time to.

**Comment by tfonfara** [comment]
@bret-fears there you go ;)

**Comment by bret-fears** [comment]
Closing this issue for now. Feel free to leave feedback here or open new issues as appropriate.

**Comment by tfonfara** [comment]
@bret-fears thanks a lot for approving and merging! Could you create a new release version from the updated master branch so this change is available as gradle dependency?

**Comment by amanzan** [comment]
Hey @bret-fears I don't think this is fixed in version 1.0.2. In the Recycler Example, I still see what @16meyrat commented: RecyclerView is animated is first fully displayed, then disappears, and then the animation starts. Is there anything I am missing?


https://user-images.githubusercontent.com/3911627/104465884-d3c04700-55b4-11eb-9dc1-36a4033b09eb.mp4

**Comment by amanzan** [comment]
Also, @tfonfara fix makes children's setStartDelay to stop working. I added the fix manually, and now all RecyclerView children animate at the same time, instead of one by one!

**Comment by bret-fears** [comment]
@amanzan I have completely forgotten about this. I will re-open and investigate possible options around it so it doesn't interfere with other types of set animations.

**Comment by bret-fears** [comment]
Fix has been merged and is available in patch version 1.0.3
